### PR TITLE
Add banner. 

### PR DESCRIPTION
**Pull request by abrardev99**

### CODE REVIEW

**Comment by stancl** [comment]
Can you also add `x-cloak` to the element? And make sure that we have the x-cloak style in the layout head.

**Comment by stancl** [comment]
And try making all of the black things like `brown-900`

**Comment by abrardev99** [comment]
Added above suggestions. Also, remove the shadow from the button.

**Comment by stancl** [comment]
Can you make sure the assets are up to date? Run the prod build

**Comment by abrardev99** [comment]
> Can you make sure the assets are up to date? Run the prod build

Done.

**Pull request merged**
